import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["500", "700"] });

export const metadata = {
  title: "American Diner UK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>NavBar</div>
        {children}
        <div>Footer</div>
      </body>
    </html>
  );
}
